image: alpine:latest
## this task runner should be runned only when pushing to production .
pages:
  stage: deploy
  script:
    - echo 'Building Site...'
    - mkdir public
    - mv dist/* public
  artifacts:
    paths:
    - public

  only:
  - prod

